version: '3.8'

services:
  app:
    image: golang:1.20-alpine
    container_name: golang-app
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "go run main.go"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - DB_NAME=mydb
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      -"5432:5432"

volumes:
  dbdata:
